on:
  push: 
    branches:
      - master

jobs:
  deploy:
    run-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: action/checkout@v3

      - name: setup Node.js
        uses: action/setup-node@v4
        with:
          node-version: '18'

      - name: install dependencies
        uses: npm install

      - name: Build Angular app
        uses: npm run build --prod

      - name: Deploy to s3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: your-s3-bucket-name
          AWS_ACCESS_KEY_ID: ${{ secret.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: your-region
          SOURCE_DIR: dist/your-app-name
